name: Quality

concurrency:
    cancel-in-progress: true
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

on:
    push:
      branches:
        - main
    pull_request:

permissions:
    contents: read

jobs:
  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: DavidAnson/markdownlint-cli2-action@v13
          with:
            globs: |
              **/*.md
              #**/.terraform/**/*.md
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
  action-lint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Actionlint
      id: get_actionlint
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
    - name: Run Actionlint
      run: ${{ steps.get_actionlint.outputs.executable }} -color
  format:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable -- component rustfmt
        rustup default stable
    - name: Check formatting
      run: cargo fmt --all --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable -- component clippy
        rustup default stable
    - name: Check clippy
      run: cargo clippy --tests --all-features -- --deny warnings
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
    - name: Run tests
      run: cargo test