name: Release
run-name: ${{inputs.release_type}}

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Which type of release is this?"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
        default: "patch"
          
permissions:
  contents: write

jobs:
  prepare:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.next_tag }}
      branch: ${{ steps.branch.outputs.branch }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
      - name: Configure git
        run: |-
          gh api /user > user.json
          git config --global user.email "$(jq -r '.email' user.json)"
          git config --global user.name "$(jq -r '.name' user.json)"
      - name: Prepare branch name
        id: branch
        run: echo "branch=release${{ github.run_id }}" >> "$GITHUB_OUTPUT"
      - name: Create branch
        run: git checkout -b "${{ steps.branch.outputs.branch }}"
      - uses: powerd6/.github/.github/actions/version_bump@main
        id: version
        with:
          release_type: ${{ inputs.release_type }}
      - name: Prepare environment variables
        run: |-
          {
            echo "CURRENT=${{steps.version.outputs.current_tag}}"
            echo "NEXT=${{steps.version.outputs.next_tag}}"
            echo "CURRENT_CARGO=${{steps.version.outputs.current_number}}"
            echo "NEXT_CARGO=${{steps.version.outputs.next_number}}"
          } >> "$GITHUB_ENV"
      - name: update Cargo.toml
        run: |-
          sed -i "s/$CURRENT_CARGO/$NEXT_CARGO/g" Cargo.toml
          git add Cargo.toml
          git commit -m "update Cargo.toml"
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
      - name: update Cargo.lock
        run: |-
          cargo build
          git add Cargo.lock
          git commit -m "update Cargo.lock"
      - name: update CHANGELOG.md
        run: |-
          head -n 13 CHANGELOG.md > changelog.md.0
          tail -n +15 CHANGELOG.md > changelog.md.1

          # Reset the file
          echo -n > CHANGELOG.md
          {
            cat changelog.md.0
            echo "## [Unreleased](https://github.com/powerd6/spec/compare/$NEXT...HEAD)"
            echo ""
            echo "## [$NEXT](https://github.com/powerd6/spec/releases/tag/$NEXT)"
            cat changelog.md.1
          } >> CHANGELOG.md

          rm changelog.md.*
          git add CHANGELOG.md
          git commit -m "update CHANGELOG.md"
      - name: Push changes
        run: git push -u origin "${{ steps.branch.outputs.branch }}"
  release:
    needs:
      - prepare
    uses: powerd6/.github/.github/workflows/s_draft_release.yml@main
    with:
      version_tag: ${{ needs.prepare.outputs.version }}
      branch: ${{ needs.prepare.outputs.branch }}
    secrets:
      GH_ADMIN_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}